### ISSUE TITLE
more a question of running on vsphere

### ISSUE THREAD

**Issue by vivekskrishna** [cluster-api-provider-k3s/cluster-api-k3s#7]
Great job on the initial tryout of creating a framework for k3s using cluster-api. Is this something that you are planning to eventually contribute upstream? is it ok if i ask for help when i try to integrate it with CAPV so that i can run k3s on vsphere environment?

**Comment by zawachte** [comment]
Hey @vivekskrishna,

Thanks for reaching out!

I don't think this repo will ever be upstreamed to the cluster-api repo considering the controlplane/bootstrap plugin model they follow. They allow the kubeadm provider to live inside of the repo, but that is because it is the default controlplane and bootstrap provider. I would like to move this repo into the kubernetes-sigs org or the k3s org, but the project probably needs some more love before making that push.

As for asking questions about CAPV, yes I would love to help out and get the installation steps merged into this repo.

I am also in between jobs at the moment, so I plan to spend some time getting this repo aligned with ClusterAPI v1beta1.

**Comment by vivekskrishna** [comment]
Thank You for the update. Meanwhile I was able to use CABP3 and CACP3 and use it with CAPV and create a single node k3s cluster(havent tried worket yet) using a vsphere based VM. I had to do small changes to get it done. I am trying to add few more capabilities in the bootstrap so that certin cloud init functionalities can be enabled. Will provide you an update once i have it working. But by and large it seemed to work fine. Nice work on these 2 modules.

**Comment by djpbessems** [comment]
I'm interested in any efforts to use CAPV with a k3s end result...

**Comment by zawachte** [comment]
I think @vivekskrishna has a fork with it working with CAPV.

**Comment by luisdavim** [comment]
Any updates on this?

**Comment by zawachte** [comment]
should we close this issue?

**Comment by luisdavim** [comment]
Yeah, this and #52 can probably be closed.
